services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ballData
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dev:dev@db:5432/ballData
      PORT: 3001
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  pgdata:
